### ISSUE TITLE
Zero mob spawns to speak of

### ISSUE THREAD

**Issue by EpsilonTheDerg** [OfficialCodeNoodles/2D-Minecraft#10]
Started up a new survival world, and for some reason I am not seeing any mobs in the world at all. No passive mobs roaming the several biomes I've visited, no hostiles roaming the caves or the night. Is there some sort of slim chance type thing or spawn wait period I've missed?

**Comment by MaximusBR8848** [comment]
Yea, I saw in the mob code and it has a error
