### ISSUE TITLE
Chests cannot be opened in creative mode

### ISSUE THREAD

**Issue by M3FF1N** [OfficialCodeNoodles/2D-Minecraft#3]
When a player tries to open a chest in creative mode, they instantly replace the chest with the block they hold. Very minor bug in a really fun game!

**Comment by OfficialCodeNoodles** [comment]
Yeah. Since the tile editor takes precedent over any block interactions, it just ends up destroying the chest. I need to actually make a proper creative mode so that this kind of stuff doesn't happen. Thanks for the comment!
