### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by joan-code6** [OfficialCodeNoodles/2D-Minecraft#56]
sry maybe i am just to silly but how can i start the game?

**Comment by Youssef-Gamer** [comment]
ok, you probably haven't used github before, but just click on "Minecraft 2D v 1.1.zip"
and you should see a download button next to "Raw" and copy, just download it, extract, and find the exe file in it

**Comment by joan-code6** [comment]
Thank you
(I already found it)
My Problem was to find the exe file
