### ISSUE TITLE
Missing files from source

### ISSUE THREAD

**Issue by Squidtito** [OfficialCodeNoodles/2D-Minecraft#9]
Howdy, I'm trying to build this project from Linux. Though I think you might've not included your UI library "Glass"? I didn't see it on your account either or maybe I'm just blind. I'm not sure if this is intentional or not. Cheers.

**Comment by DoubleShotgun** [comment]
You're blind.
https://github.com/OfficialCodeNoodles/2D-Minecraft/blob/main/2D Minecraft v 1.0/Glass 4.0 UI API.dll
CodeNoodle hasn't made his Library open source yet.
